### ISSUE TITLE
Hexo主题Cards版权信息部分未支持文章Front Matter自定义作者字段

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#136]
## 描述：

当前Hexo主题 **Cards** 中的版权信息部分（`copyright.ejs`）无法正确支持文章Front Matter中的自定义作者字段。无论是否在Front Matter中为某篇文章指定了作者，版权信息部分都会显示 `_config.cards.yml` 文件中全局配置的默认作者（`theme.meta.author.name`）。

这种行为导致在多作者博客、客座作者文章等场景下，无法为单篇文章指定不同的作者。这限制了主题的灵活性，并且与用户期望的自定义行为不符。

## 当前行为：
在原始的 `copyright.ejs` 文件中，版权部分的作者字段总是直接从 `theme.meta.author.name` 中获取，而不检查文章Front Matter中是否定义了 `author` 字段。

https://github.com/ChrAlpha/hexo-theme-cards/blob/100791d5a417acc2109e4669eaf2da755ea15633/layout/_meta/copyright.ejs#L4

如下是当前的 `copyright.ejs` 文件代码：

```ejs
<% if (theme.meta.copyright.enable && page.copyright !== false) { %>
    <div class="post__license">
        <p>
            <strong><%= __('post.copyright.author') %></strong><%= theme.meta.author.name %>
        </p>
        <p>
            <strong>
                <%= __('post.copyright.permalink') %>
            </strong>
            <a href="<%= page.permalink %>"><%= page.permalink %></a>
        </p>
        <% (theme.meta.copyright.custom_text || []).forEach((text) => { %>
            <strong>
                <%- markdown(text) %>
            </strong>
        <% }); %>
    </div>
<% } %>
```

在这种实现中：
- 无论Front Matter中是否定义了自定义作者字段，版权部分的作者总是显示 `_config.cards.yml` 中的默认作者（`theme.meta.author.name`）。
- 例如，如果 `_config.cards.yml` 中包含以下内容：
  ```yaml
  meta:
    author:
      name: "默认作者"
      url: "https://defaultauthor.com"
  ```
  那么所有文章的版权部分都会显示：
  ```
  作者：默认作者
  ```

即使某篇文章的Front Matter中指定了以下内容：
```yaml
author:
  name: "自定义作者"
```
仍然无法覆盖全局默认作者。

## 预期行为：
在每篇文章的Front Matter中支持自定义作者字段。如果Front Matter中定义了 `author.name`，版权信息部分应显示自定义作者；如果Front Matter中没有定义 `author`，则回退到 `_config.cards.yml` 中的默认作者。

例如：
1. 如果某篇文章的Front Matter如下：
   ```yaml
   ---
   title: 测试文章
   date: 2024-11-28
   author:
     name: "自定义作者"
     url: "https://customauthor.com"
   ---
   ```
   版权部分应显示：
   ```
   作者：自定义作者
   ```

2. 如果Front Matter中没有定义 `author`，例如：
   ```yaml
   ---
   title: 测试文章
   date: 2024-11-28
   ---
   ```
   则版权部分应显示全局默认作者：
   ```
   作者：默认作者
   ```

## 复现步骤：
1. 设置 `_config.cards.yml`：
   ```yaml
   meta:
     author:
       name: "默认作者"
       url: "https://defaultauthor.com"
   ```
2. 创建一篇包含以下Front Matter的文章：
   ```yaml
   ---
   title: 测试文章
   date: 2024-11-28
   author:
     name: "自定义作者"
   ---
   ```
3. 执行 `hexo g` 生成网站。
4. 打开生成的文章页面，观察版权部分。实际结果为：
   ```
   作者：默认作者
   ```
   而不是预期的：
   ```
   作者：自定义作者
   ```

## 问题根因：
模板文件 `copyright.ejs` 并未检查 `page.author`，而是直接输出 `theme.meta.author.name`。这导致即使在文章Front Matter中定义了 `author`，也无法覆盖全局默认作者。

## 修复建议：
通过修改 `copyright.ejs` 文件，使其优先检查 `page.author.name`，在未定义时才回退到全局默认作者（`theme.meta.author.name`）。以下是修改后的代码：

### 修改后的 `copyright.ejs`：
```ejs
<% if (theme.meta.copyright.enable && page.copyright !== false) { %>
    <div class="post__license">
        <p>
            <strong><%= __('post.copyright.author') %></strong>
            <%= page.author && page.author.name ? page.author.name : theme.meta.author.name %>
        </p>
        <p>
            <strong>
                <%= __('post.copyright.permalink') %>
            </strong>
            <a href="<%= page.permalink %>"><%= page.permalink %></a>
        </p>
        <% (theme.meta.copyright.custom_text || []).forEach((text) => { %>
            <strong>
                <%- markdown(text) %>
            </strong>
        <% }); %>
    </div>
<% } %>
```

### 修改说明：
- 新增了一段逻辑：
  ```ejs
  <%= page.author && page.author.name ? page.author.name : theme.meta.author.name %>
  ```
  这段代码优先检查 `page.author.name` 是否存在。如果存在，则使用文章Front Matter中定义的作者；否则回退到全局默认作者。

## 为什么需要修复：
1. **多作者博客支持**：许多博客需要支持为不同文章设置不同的作者，例如团队协作博客或包含客座作者的博客。当前的实现限制了这一需求。
2. **灵活性**：让Front Matter的设置优先于全局配置，是更灵活、更符合用户预期的行为。
3. **与Hexo惯例一致**：大多数Hexo主题支持通过Front Matter覆盖全局配置，这种行为应当被延续。

## 其他上下文：
- **Hexo版本**：`5.2.0`
- **Cards主题版本**：`1.4.2` - `1.5.1` 都有这个问题
- `_config.cards.yml` 示例：
  ```yaml
  meta:
    author:
      name: "默认作者"
      url: "https://defaultauthor.com"
  ```

如需更多测试或让我提出 Pull Request，我都方便。

## 感谢

最后，我想向你表达我最诚挚的感谢。你的 Cards 主题陪伴了我的博客好几年，见证了我从学生时代到工作。它不仅仅是一个主题，更像是我博客的灵魂，与我的写作风格融为一体。即使在时光流转、技术不断更新的今天，Cards 依然能让我觉得它是经得起时间考验的经典之作。

感谢你用心打造了这样一款作品，它不仅服务了像我这样的博主，更让我们能够通过它更有温度地表达自我。愿 Cards 主题持续散发光芒，陪伴更多的博主走过他们的写作之路！
