### ISSUE TITLE
thumbnail字段问题

### ISSUE THREAD

**Issue by bronya5th** [ChrAlpha/hexo-theme-cards#51]
cards主题升级到1.1.0版本后，‘thumbnail’字段为true无法在主页看到缩略图显示，是我的lazyload配置不对么？
我的thumbnail配置：
```
# 文章缩略图
  thumbnail: 
    enable: true
    default:   # 默认缩略图，当页面 `thumbnail` 字段为空时 fallback 至此参数
```
lazyload配置：
```
# 图片懒加载插件
lazyload:
  enable: true
  onlypost: false
  loadingImage: 
```
hexo --version：
- hexo: 5.2.0
- hexo-cli: 3.1.0
- os: Windows_NT 10.0.18363 win32 x64
