### ISSUE TITLE
Google Analytics 不生效

### ISSUE THREAD

**Issue by hayschan** [ChrAlpha/hexo-theme-cards#60]
配置为
```yaml
analytics:
  google_site_id:
  gtags_site_id: UA-66467516-5
```
可是，过去一周都没收到任何流量。对网页进行 Show Page Source，也没找到 gtag 的 script。
网站：[haysc.tech](https://haysc.tech)
