### ISSUE TITLE
代码高亮色 设置不生效

### ISSUE THREAD

**Issue by LeeWongSnail** [ChrAlpha/hexo-theme-cards#72]
站点配置文件如下
```
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```
主题配置文件中

```
# 默认代码高亮
  highlight: 

    # 默认代码高亮主题
    default: vs

    # 暗色代码高亮主题
    darkmode: vs
```
这里的主题是支持https://highlightjs.org/   官方的这些主题的吧
改了之后没有效果 还是我操作有问题

**Comment by Yu040419** [comment]
目前我也有這個問題，並分別做以下配置，想請問還有哪裡操作不完全呢？
```
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""
```
以上為 hexo 的設定檔，以下為主題的設定檔：
```
highlight:
    default: github

venders:
  highlight: https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2.2/dist/css/highlight/github.min.css
```
感謝！
