### ISSUE TITLE
代码高亮设置的相关问题

### ISSUE THREAD

**Issue by JoshuaLai01** [ChrAlpha/hexo-theme-cards#79]
作者你好，根据你的帮助文档，在做出以下修改后，发现并没有出现预期的效果，请问我是哪里出现了问题？
预期：使用原生Highlight.js的tom-one-dark主题。

1. 站点配置文件
```
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: false
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''
```

2. 主题配置文件
```
style:
  hljs: 

    # 默认代码高亮主题
    default: atom-one-dark

    # 暗色代码高亮主题
    darkmode: atom-one-dark
```
```
vendors:
  hljs: https://cdn.jsdelivr.net/npm/highlight.js@10.4.0/styles/
```
实际效果
![image](https://user-images.githubusercontent.com/46258498/103020989-69535280-4584-11eb-9547-feba5dd71f3d.png)
![image](https://user-images.githubusercontent.com/46258498/103021051-7d974f80-4584-11eb-9d62-b281084c9eb0.png)
