### ISSUE TITLE
关于友链的功能怎么使用

### ISSUE THREAD

**Issue by majikoo1028** [ChrAlpha/hexo-theme-cards#83]
请教一下博主，那个友链在哪里添加，什么格式，才能正常显示

**Comment by bronya5th** [comment]
在站点 source 文件夹下创建一个以 .md 为后缀的文件，front-matter里填上
```
---
layout: links
---
```
友链数据放在front-matter里。.md文件完整配置如下。（此处使用[ChrAlpha](https://github.com/ChrAlpha/Friends)的部分友链数据）
```
---
layout: links
links: 
  - name: ChrAlpha Blog
    url: https://chralpha.com
    avatar: https://cdn.jsdelivr.net/npm/chrdnx@1.0.10/img/head-round.png
    target: _blank
    backgroundColor: '#fff'
    textColor: '#444'  
  - name: ChrAlpha Blog
    url: https://chralpha.com
    avatar: https://cdn.jsdelivr.net/npm/chrdnx@1.0.10/img/head-round.png
    target: _blank
    backgroundColor: '#fff'
    textColor: '#444'
  - name: "P3TERX ZONE"
    avatar: p3terx.com.jpeg
    url: https://p3terx.com/
    desc: "一个萌新的博客"
  - name: "科技花"
    avatar: blog.zaihua.me.png
    url: https://blog.zaihua.me/
    desc: "一条猛男"
  - name: "执迷不悟"
    avatar: ditou.org.png
    url: https://ditou.org/
    desc: "friend"
---

```
更多添加/修改的友链方式请参考[hexo-theme-cards](https://github.com/ChrAlpha/hexo-theme-cards)的官方文档[独立页面](https://theme-cards.ichr.me/pages/)
