### ISSUE TITLE
关于search功能的配置

### ISSUE THREAD

**Issue by majikoo1028** [ChrAlpha/hexo-theme-cards#91]
search功能应该咋配置，我search功能置true后只能打开search页面，搜索站内内容的时候没有显示搜索结果

**Comment by ChrAlpha** [comment]
如果搜索了不存在的内容自然是不会有结果的，你可以点击以下两个链接对比下

https://blog.ichr.me/search/?s=hexo

https://blog.ichr.me/search/?s=blablabla

关于无结果的反馈正在考虑中

**Comment by majikoo1028** [comment]
内容存在我是可以肯定地，我感觉应该是哪的配置出了问题，我看博主你的就有结果反馈

**Comment by majikoo1028** [comment]
这是我博客，博主有空可以去看看[https://unbelievable.cool/](https://unbelievable.cool/)，搜索用不了有点苦恼...

**Comment by ChrAlpha** [comment]
![image](https://user-images.githubusercontent.com/53332481/113499028-fd01cb00-9544-11eb-8b12-c03f6e1ebda0.png)

这里出错了，能否提供主题目录下 `layout/_plugins/search/local-search/source.ejs` 文件及主题配置文件中的 `search.path`、`vendors.local_search` 两项配置以供排错？

**Comment by majikoo1028** [comment]
这是`source.ejs`
```
<div id="search-card">
    <form class="search-form" autocomplete="off">
        <div class="search-input">
            <input maxlength="80" type="search" class="search-input" id="search-input" name="s" placeholder="<%= __('search.placeholder') %>" required>
        </div>
        <div class="search-button">
            <button class="search-button " type="submit"><%= __('search.main') %></button>
        </div>
    </form>
</div>
<div id="search-result"></div>
<script>var searchDataFile = "<%= url_for(theme.search.path) %>";</script>
<script defer src="<%= url_for(theme.vendors.local_search || 'js/local-search.js') %>"></script>
```

这是另外两个的内容
```
# 站内搜索插件
search:
  enable: true
  path: \search\
  field: All  # Page | Post | All

local_search: 
    enable: true
```

**Comment by ChrAlpha** [comment]
主题配置文件中相关配置改为：

```yaml
search:
  enable: true
  path: /search.json
  field: All  # Page | Post | All

local_search: js/local-search.js
```

`search.path` 必须为 JSON 文件，`vendors.local_search` 是存放静态资源的地址而非开关，不需要也更不能填 `enable: true`。参见 [主题文档](https://theme-cards.ichr.me/)。
